# Generated by Django 5.1.1 on 2025-01-03 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LaunchRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('departure_time', models.DateTimeField()),
                ('cabin_class', models.IntegerField(default=0)),
                ('cabin_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ac_chair_class', models.IntegerField(default=0)),
                ('ac_chair_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('chair_class', models.IntegerField(default=0)),
                ('chair_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='LaunchBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('seat_class', models.CharField(max_length=50)),
                ('seats_reserved', models.IntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(default='booked', max_length=20)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='launch.launchroute')),
            ],
        ),
    ]
