# Generated by Django 5.1.1 on 2024-12-04 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('departure_time', models.DateTimeField()),
                ('economy_seats', models.PositiveIntegerField(default=0)),
                ('economy_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('business_seats', models.PositiveIntegerField(default=0)),
                ('business_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('general_seats', models.PositiveIntegerField(default=0)),
                ('general_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='AirBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('seat_class', models.CharField(max_length=50)),
                ('seats_reserved', models.IntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='air.airroute')),
            ],
        ),
    ]
