# Generated by Django 5.1.1 on 2024-12-12 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airroute',
            name='business_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='airroute',
            name='business_seats',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='airroute',
            name='economy_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='airroute',
            name='economy_seats',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='airroute',
            name='general_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='airroute',
            name='general_seats',
            field=models.IntegerField(default=0),
        ),
    ]
