# Generated by Django 5.1.1 on 2025-01-03 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air', '0002_alter_airroute_business_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airroute',
            old_name='business_seats',
            new_name='business_class',
        ),
        migrations.RenameField(
            model_name='airroute',
            old_name='economy_seats',
            new_name='economy_class',
        ),
        migrations.RenameField(
            model_name='airroute',
            old_name='general_seats',
            new_name='first_class',
        ),
        migrations.AddField(
            model_name='airbooking',
            name='status',
            field=models.CharField(default='booked', max_length=20),
        ),
    ]
