# Generated by Django 5.1.1 on 2024-12-12 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0002_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='journey_choice',
            field=models.CharField(blank=True, choices=[('Bus', 'Bus'), ('Air', 'Air'), ('Launch', 'Launch'), ('Train', 'Train')], max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profession',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
