# Generated by Django 5.1.1 on 2025-01-03 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0004_alter_userprofile_profile_picture_travelexperience_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelexperience',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_experiences', to=settings.AUTH_USER_MODEL),
        ),
    ]
