# Generated by Django 5.1.1 on 2024-11-26 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BusRoute',
        ),
    ]
