# Generated by Django 5.1.1 on 2024-12-02 20:36

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Main', '0007_employee_employeeactivity_normaluser_and_more'),
        ('employee', '0004_delete_busroute'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeActivity',
            fields=[
            ],
            options={
                'verbose_name': 'Employee Activity',
                'verbose_name_plural': 'Employee Activities',
                'db_table': 'employee_activity',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Main.useractivity',),
        ),
    ]
