# Generated by Django 5.1.1 on 2024-12-03 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_alter_employeeactivity_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeactivity',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee'),
        ),
    ]
