# Generated by Django 5.1.1 on 2024-11-25 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_customuser_designation_customuser_employee_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
