# Generated by Django 5.1.1 on 2024-12-02 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0006_useractivity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Main.customuser',),
        ),
        migrations.CreateModel(
            name='EmployeeActivity',
            fields=[
            ],
            options={
                'verbose_name': 'Employee Activity',
                'verbose_name_plural': 'Employee Activities',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Main.useractivity',),
        ),
        migrations.CreateModel(
            name='NormalUser',
            fields=[
            ],
            options={
                'verbose_name': 'Normal User',
                'verbose_name_plural': 'Normal Users',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Main.customuser',),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='employee_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
