# Generated by Django 5.1.1 on 2024-12-02 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0007_employee_employeeactivity_normaluser_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='EmployeeActivity',
        ),
        migrations.DeleteModel(
            name='NormalUser',
        ),
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
