# Generated by Django 5.1.1 on 2024-11-26 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainroute',
            name='available_seats',
        ),
        migrations.RemoveField(
            model_name='trainroute',
            name='price',
        ),
        migrations.AddField(
            model_name='trainroute',
            name='ac_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='trainroute',
            name='ac_seats',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trainroute',
            name='first_class_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='trainroute',
            name='first_class_seats',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trainroute',
            name='shovan_chair_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='trainroute',
            name='shovan_chair_seats',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trainroute',
            name='shovan_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='trainroute',
            name='shovan_seats',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trainroute',
            name='shulov_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='trainroute',
            name='shulov_seats',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
