# Generated by Django 5.1.1 on 2024-12-02 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0002_remove_trainroute_available_seats_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='seats',
        ),
        migrations.AddField(
            model_name='booking',
            name='seat_class',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='seats_reserved',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
