# Generated by Django 5.1.1 on 2025-01-03 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0004_rename_customer_email_booking_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(default='booked', max_length=20),
        ),
    ]
