# Generated by Django 5.1.1 on 2025-01-02 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0003_remove_booking_status_booking_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='payment_status',
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(default='reserved', max_length=20),
        ),
    ]
